# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20161203_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_daily', models.BooleanField(default=True)),
                ('is_weekly', models.BooleanField(default=False)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Frequency'),
        ),
        migrations.DeleteModel(
            name='DictFrequency',
        ),
    ]
