# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20161203_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionanimals',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='subscriptionanimals',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptiondatemail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscriptiondatemail',
            name='subscription',
        ),
        migrations.AddField(
            model_name='frequency',
            name='interval',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequency',
            name='is_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frequency',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='is_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='frequency',
            field=models.CharField(choices=[('0', 'daily'), ('1', 'weekly'), ('2', 'monthly'), ('3', 'yearly')], max_length=1),
        ),
        migrations.DeleteModel(
            name='DictAnimals',
        ),
        migrations.DeleteModel(
            name='DictDateMail',
        ),
        migrations.DeleteModel(
            name='SubscriptionAnimals',
        ),
        migrations.DeleteModel(
            name='SubscriptionDateMail',
        ),
    ]
