# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20161203_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='is_monthly',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='is_weekly',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='is_yearly',
        ),
    ]
