# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20161203_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cat', models.BooleanField(default=False)),
                ('is_dog', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='frequency',
            name='interval',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='animals',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Animal'),
            preserve_default=False,
        ),
    ]
