# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20161203_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 37, 28, 910153)),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='interval',
            field=models.CharField(default='', max_length=100),
        ),
    ]
