# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20161203_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 14, 45, 45, 205181)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 45, 45, 205216)),
        ),
    ]
